version: '3'

services:
  nextcloud-db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - db.env

  nextcloud-redis:
    image: redis:alpine
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html
    env_file:
      - db.env
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud-web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud-app

  nextcloud-cron:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
    depends_on:
      - nextcloud-web