version: '3'
services:
  sevpn_server:
    image: siomiz/softethervpn:debian
    volumes:
      - ./vpn_server.config:/usr/vpnserver/vpn_server.config:rw
    network_mode: host
    restart: unless-stopped
    cap_add:
      - ALL
