version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/backups:/var/syncthing
      - ./syncthing:/var/syncthing/config
    network_mode: host
    restart: unless-stopped
