version: "3"
services:
# web & reverse proxy
  reverse_proxy:
    image: nginx:stable-alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./www:/var/www:rw
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - speedtest
  
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    image: openspeedtest/latest